version: "3.9"

services:
  api:
    build: .
    container_name: tea_api
    restart: unless-stopped
    depends_on:
      - mongodb
      - redis
    env_file:
      - .env
    environment:
      - PORT=${PORT}
      - MONGODB_URI=${MONGODB_URI:-mongodb://mongodb:27017/tea_feed}
      - REDIS_URL=${REDIS_URL:-redis://redis:6379}
      - SYNC_INDEXES=${SYNC_INDEXES:-true}
    ports:
      - "3000:3000"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
  mongodb:
    image: mongo:7
    container_name: tea_mongodb
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    container_name: tea_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  mongo_data:
  redis_data:


